site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md

theme:
  name: material
  language: es
  features: 
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - announce.dismiss
  logo: assets/logo.png
  palette:
    - scheme: slate
    - primary: deep orange
    # Paleta para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Paleta para modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  plugins:
  - search
  font:
    code: Oswald
  extra:
    social:
      - icon: assets/insta.jpg
        link: https://www.instagram.com/aalexx_63/