site_name: IAW

nav:
    - Principal: index.md
    - Practica1.7: practica1-7.md
    - Practica1.9: practica1-9.md
    - Acerca de: about.md

theme:
  name: material
  language: es
  extra:
    social:
      - icon: assets/insta.jpg
        link: https://www.instagram.com/aalexx_63/
  features: 
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - announce.dismiss
  logo: assets/logo.png
  palette:
    - primary: deep orange
    - scheme: slate
  plugins:
  - search
  font:
    code: Oswald